export const data=[
    {
        id:1,
        name:'1010 Steiner St',
        image:['https://media.istockphoto.com/id/1458854866/photo/modern-living-room-interior-with-television-set-sofa-armchair-floor-lamp-and-coffee-table.jpg?s=612x612&w=0&k=20&c=Iidm8woVPQxcpP5vIsb-LyjCRcf0Tij1HTkXYXfYnoU=', 'https://media.istockphoto.com/id/1158066632/photo/modern-living-room.jpg?s=612x612&w=0&k=20&c=eBBjs47r1VUmc3Z47XDU5hdjOUSgdLeHia4qIWHNd-Y='],
        description:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ',
        location:'123 Oak Street, City Center, Anytown, USA',
        rent:'Rent',
        bedrooms:2,
        square:'10000',
        year:'2013',
        baths:3,
        price:'3,450,000',
        latitude:37.7787714,
        longitude:-122.43324
        
    },
    {
        id:2,
        name:'1100 sacramento St',
        image:['https://th.bing.com/th?q=Male+Placeholder&w=120&h=120&c=1&rs=1&qlt=90&cb=1&pid=InlineBlock&mkt=en-WW&cc=NG&setlang=en&adlt=moderate&t=1&mw=247','https://th.bing.com/th/id/OIP.wzozBZQGxEoouVJ5V-1bwAHaHN?w=177&h=180&c=7&r=0&o=5&pid=1.7','https://th.bing.com/th/id/OIP.1Wn1tdSunnfamZC6T_HA6wAAAA?w=203&h=176&c=7&r=0&o=5&pid=1.7 '],
        description:'It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        location:'456 Maple Avenue, Suburbia, Anycity, USA',
        rent:'Buy',
        bedrooms:3,
        square:'$5000',
        year:'2010',
        baths:5,
        price:'2,400,000',
        latitude:37.7929478,
        longitude:-122.411419
    },
    {
        id:3,
        name:'76 Saturn St',
        image:['https://th.bing.com/th?q=Male+Placeholder&w=120&h=120&c=1&rs=1&qlt=90&cb=1&pid=InlineBlock&mkt=en-WW&cc=NG&setlang=en&adlt=moderate&t=1&mw=247','https://th.bing.com/th/id/OIP.wzozBZQGxEoouVJ5V-1bwAHaHN?w=177&h=180&c=7&r=0&o=5&pid=1.7','https://th.bing.com/th/id/OIP.1Wn1tdSunnfamZC6T_HA6wAAAA?w=203&h=176&c=7&r=0&o=5&pid=1.7 '],
        description:'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using , making it look like readable English.',
        location:'789 Elm Court, Downtown, Anytown, USA',
        rent:'Buy',
        bedrooms:4,
        square:'2,500',
        year:'2017',
        baths:6.5,
        price:'1,050,000',
        latitude: 37.762839,
        longitude:-122.442522
    },
    {
        id:4,
        name:'68 Rosemont St',
        image:['https://th.bing.com/th?q=Male+Placeholder&w=120&h=120&c=1&rs=1&qlt=90&cb=1&pid=InlineBlock&mkt=en-WW&cc=NG&setlang=en&adlt=moderate&t=1&mw=247','https://th.bing.com/th/id/OIP.wzozBZQGxEoouVJ5V-1bwAHaHN?w=177&h=180&c=7&r=0&o=5&pid=1.7','https://th.bing.com/th/id/OIP.1Wn1tdSunnfamZC6T_HA6wAAAA?w=203&h=176&c=7&r=0&o=5&pid=1.7 '],
        description:'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using , making it look like readable English.',
        location:'321 Pine Lane, Lakeside, Anycity, USA',
        rent:'Rent',
        bedrooms:3,
        square:'2,500',
        year:'2011',
        baths:4,
        price:'5,000,000',
        latitude:37.7682862,
        longitude:-122.4258278
    },
    {
        id:5,
        name:'4023 Folsom St',
        image:['https://th.bing.com/th?q=Male+Placeholder&w=120&h=120&c=1&rs=1&qlt=90&cb=1&pid=InlineBlock&mkt=en-WW&cc=NG&setlang=en&adlt=moderate&t=1&mw=247','https://th.bing.com/th/id/OIP.wzozBZQGxEoouVJ5V-1bwAHaHN?w=177&h=180&c=7&r=0&o=5&pid=1.7','https://th.bing.com/th/id/OIP.1Wn1tdSunnfamZC6T_HA6wAAAA?w=203&h=176&c=7&r=0&o=5&pid=1.7 '],
        description:'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using , making it look like readable English.',
        location:'654 Cedar Road, Mountain View, Anytown, USA',
        rent:'Rent',
        bedrooms:4,
        square:'1000',
        year:'2006',
        baths:3,
        price:'2,550,000',
        latitude:37.736359199999995,
        longitude:-122.41337779999999
    },

    {
        id:6,
        name:'1200 Market St',
        image:['https://th.bing.com/th?q=Male+Placeholder&w=120&h=120&c=1&rs=1&qlt=90&cb=1&pid=InlineBlock&mkt=en-WW&cc=NG&setlang=en&adlt=moderate&t=1&mw=247','https://th.bing.com/th/id/OIP.wzozBZQGxEoouVJ5V-1bwAHaHN?w=177&h=180&c=7&r=0&o=5&pid=1.7','https://th.bing.com/th/id/OIP.1Wn1tdSunnfamZC6T_HA6wAAAA?w=203&h=176&c=7&r=0&o=5&pid=1.7 '],
        description:'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using , making it look like readable English.',
        location:'987 Birch Street, Historic District, Anycity, USA',
        rent:'Rent',
        bedrooms:3,
        square:'1500',
        year:'2004',
        baths:4,
        price:'3,550,000',
        latitude:37.7786745,
        longitude:-122.413529139999999
    },
    {
        id:7,
        name:'278 Brannan St',
        image:['https://th.bing.com/th?q=Male+Placeholder&w=120&h=120&c=1&rs=1&qlt=90&cb=1&pid=InlineBlock&mkt=en-WW&cc=NG&setlang=en&adlt=moderate&t=1&mw=247','https://th.bing.com/th/id/OIP.wzozBZQGxEoouVJ5V-1bwAHaHN?w=177&h=180&c=7&r=0&o=5&pid=1.7','https://th.bing.com/th/id/OIP.1Wn1tdSunnfamZC6T_HA6wAAAA?w=203&h=176&c=7&r=0&o=5&pid=1.7 '],
        description:'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using , making it look like readable English.',
        location:'741 Spruce Avenue, Beachfront, Anytown, USA',
        rent:'Buy',
        bedrooms:3,
        square:'2000' ,
        year:'2010',
        baths:4,
        price:'2,550,000',
        latitude:37.736359199999995,
        longitude:-122.41337779999999
    },
    {
        id:8,
        name:'One Mission Bay',
        image:['https://th.bing.com/th?q=Male+Placeholder&w=120&h=120&c=1&rs=1&qlt=90&cb=1&pid=InlineBlock&mkt=en-WW&cc=NG&setlang=en&adlt=moderate&t=1&mw=247','https://th.bing.com/th/id/OIP.wzozBZQGxEoouVJ5V-1bwAHaHN?w=177&h=180&c=7&r=0&o=5&pid=1.7','https://th.bing.com/th/id/OIP.1Wn1tdSunnfamZC6T_HA6wAAAA?w=203&h=176&c=7&r=0&o=5&pid=1.7 '],
        description:'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using , making it look like readable English.',
        location:'852 Willow Lane, Urban Suburb, Anycity, USA',
        rent:'Buy',
        bedrooms:6,
        square:'2000',
        year:'2004',
        baths:3,
        price:'4,550,000',
        latitude:37.7747908,
        longitude:-122.39107910000001
    },
    {
        id:9,
        name:'837 Union St',
        image:['https://th.bing.com/th?q=Male+Placeholder&w=120&h=120&c=1&rs=1&qlt=90&cb=1&pid=InlineBlock&mkt=en-WW&cc=NG&setlang=en&adlt=moderate&t=1&mw=247','https://th.bing.com/th/id/OIP.wzozBZQGxEoouVJ5V-1bwAHaHN?w=177&h=180&c=7&r=0&o=5&pid=1.7','https://th.bing.com/th/id/OIP.1Wn1tdSunnfamZC6T_HA6wAAAA?w=203&h=176&c=7&r=0&o=5&pid=1.7 '],
        description:'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using , making it look like readable English.',
        location:'369 Magnolia Drive, Residential Area, Anytown, USA',
        rent:'Rent',
        bedrooms:5,
        square:'3000',
        year:'2000',
        baths:6,
        price:'1,550,000',
        latitude:37.79951799999995,
        longitude:-122.41304419999999
    },
]